export const users = [
    { id: 1, username: "tech_guru99", email: "techguru99@example.com" },
    { id: 2, username: "sneakyCoder", email: "sneakycoder@example.com" },
    { id: 3, username: "data_diva", email: "datadiva@example.com" },
    { id: 4, username: "noobmaster47", email: "noobmaster47@example.com" },
    { id: 5, username: "frontendFreak", email: "frontendfreak@example.com" },
    { id: 6, username: "backendBoss", email: "backendboss@example.com" },
    { id: 7, username: "debug_dan", email: "debugdan@example.com" },
    { id: 8, username: "cloud_crusader", email: "cloudcrusader@example.com" },
    { id: 9, username: "ui_unicorn", email: "uiunicorn@example.com" },
    { id: 10, username: "ml_monkey", email: "mlmonkey@example.com" },
];

export const products = [
    {
        id: 1,
        name: "Wireless Mouse",
        price: 799,
        category: "Electronics",
        inStock: true,
    },
    {
        id: 2,
        name: "Bluetooth Headphones",
        price: 1599,
        category: "Electronics",
        inStock: true,
    },
    {
        id: 3,
        name: "Running Shoes",
        price: 2499,
        category: "Footwear",
        inStock: false,
    },
    {
        id: 4,
        name: "Coffee Mug",
        price: 299,
        category: "Kitchen",
        inStock: true,
    },
    {
        id: 5,
        name: "Notebook (Pack of 3)",
        price: 149,
        category: "Stationery",
        inStock: true,
    },
    {
        id: 6,
        name: "LED Desk Lamp",
        price: 999,
        category: "Home Decor",
        inStock: false,
    },
    {
        id: 7,
        name: "Gaming Keyboard",
        price: 1999,
        category: "Electronics",
        inStock: true,
    },
    {
        id: 8,
        name: "Cotton T-shirt",
        price: 499,
        category: "Apparel",
        inStock: true,
    },
    {
        id: 9,
        name: "Water Bottle (1L)",
        price: 199,
        category: "Fitness",
        inStock: true,
    },
    {
        id: 10,
        name: "Smart Watch",
        price: 3499,
        category: "Electronics",
        inStock: false,
    },
];
